server:
  port: 8011
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/training?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    thymeleaf:
      cache: false
      mode: LEGACYHTML5

logging:
  level:
    com:
      dalaoyang:
        dao:
          UserMapper: debug

mybatis-plus:
  mapper-locations: classpath:com.syy.hardware.dao/*.xml
  type-aliases-package: com.syy.hardware.entity
  global-config:
    logic-delete-value: 0
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#  打印SQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
